### ISSUE TITLE
Is download code part still working?

### ISSUE THREAD

**Issue by Tazintosh** [jlnbxn/rawpixel-cc0-downloader#1]
Hi,
I'm trying to use my API tool to reproduce line 59 to 63 on your code.
I'm getting a 404.
However, if I change the `https://www.rawpixel.com/download/${id}/jpeg` to `https://www.rawpixel.com/api/v1/image/download/${id}/jpeg` I get a 401 Unauthorized.

Do you know if rawpixel changed their authentication process?

**Comment by jlnbxn** [comment]
Hello, thank you for pointing this out! In addition to the changed API url, it appears that an additional token is required, which can be attained by the session cookie. It seems to be working again for now.

**Comment by Tazintosh** [comment]
Hi, thanks for the answer.
I'm still not able to trigger a download, even by using my Cookie value as header of my request.
Did you actually got it working?
Would you mind sharing the cURL example for instance?

Edit: sorry, I didn't saw you edited the code with the token part.
I'll try to get it.

**Comment by Tazintosh** [comment]
Got the token, but still get a 401 error when trying the download a public domain image.
Has your user account anything special?
Do you have a working image ID I can test with?

**Comment by jlnbxn** [comment]
Here's an ID that I just verified: 2455286
No, just a normal account.
I'm using node version v18.12.1 if that makes any difference!

**Comment by Tazintosh** [comment]
Got it!!!
I was not using the good value for the cookie. But I noticed you updated the readme.md yesterday with "NAME_OF_COOKIE=VALUE_OF_COOKIE". Solved it all.

Thank you so much!
